In [1]:
# Import & Upload Files
from google.colab import files
uploaded = files.upload()

Saving US_RETAIL_DATA.xlsx to US_RETAIL_DATA.xlsx

In [ ]:
# Import Pandas
import pandas as pd

# Read Excel Files in the DataFrame
df = pd.read_excel("US_RETAIL_DATA.xlsx")

# Print DataFrame
print(df)

In [17]:
# Standard Deviation for Each Columns (Columns - Vertically - axis=0 - default)
# df.std(numeric_only=True)

df.std(numeric_only=True)

Quantity         2.872475
Unit Price     142.626275
Discount         0.069784
Sales         1043.840801
Profit         226.854040
dtype: float64

In [18]:
# Standard Deviation for Each Rows (Rows - Horizontally - axis=1)
# df.std(numeric_only=True,axis=1)

df.std(numeric_only=True,axis=1)

0      1088.204049
1        26.417395
2       474.142675
3       340.015389
4       434.186794
          ...
995      96.877111
996      54.429118
997     429.913240
998      81.610406
999     382.932355
Length: 1000, dtype: float64

In [29]:
# Population Standard Deviation - ddof=0
# ddof - Delta Degrees of Freedom
# df.std(ddof=0)

df.std(numeric_only=True,ddof=0)

Quantity         2.871039
Unit Price     142.554944
Discount         0.069749
Sales         1043.318750
Profit         226.740584
dtype: float64

In [20]:
# Sample Standard Deviation - ddof=1 (default)
# ddof - Delta Degrees of Freedom
# df.std(ddof=1)

df.std(numeric_only=True,ddof=1)

Quantity         2.872475
Unit Price     142.626275
Discount         0.069784
Sales         1043.840801
Profit         226.854040
dtype: float64

In [ ]:
# Combination of Mean & Standard Deviation
# Accepts "Numerical Data" only
df.agg(['mean','std'])