In [1]:
# Import & Upload Files
from google.colab import files
uploaded = files.upload()

Saving US_RETAIL_DATA.xlsx to US_RETAIL_DATA.xlsx

In [ ]:
# Import Pandas
import pandas as pd

# Read Excel Files in the DataFrame
df = pd.read_excel("US_RETAIL_DATA.xlsx")

# Print DataFrame
print(df)

In [11]:
# Variance for Each Columns (Columns - Vertically - axis=0 - default)
# df.var(numeric_only=True)

df.var(numeric_only=True)

Quantity      8.251115e+00
Unit Price    2.034225e+04
Discount      4.869780e-03
Sales         1.089604e+06
Profit        5.146276e+04
dtype: float64

In [10]:
# Variance for Each Rows (Rows - Horizontally - axis=1)
# df.var(numeric_only=True,axis=1)

df.var(numeric_only=True,axis=1)

0      1.184188e+06
1      6.978788e+02
2      2.248113e+05
3      1.156105e+05
4      1.885182e+05
           ...
995    9.385175e+03
996    2.962529e+03
997    1.848254e+05
998    6.660258e+03
999    1.466372e+05
Length: 1000, dtype: float64

In [9]:
# Population Variance - ddof=0
# ddof - Delta Degrees of Freedom
# df.var(ddof=0)

df.var(numeric_only=True,ddof=0)

Quantity      8.242864e+00
Unit Price    2.032191e+04
Discount      4.864910e-03
Sales         1.088514e+06
Profit        5.141129e+04
dtype: float64

In [8]:
# Sample Variance - ddof=1 (default)
# ddof - Delta Degrees of Freedom
# df.var(ddof=1)

df.var(numeric_only=True,ddof=1)

Quantity      8.251115e+00
Unit Price    2.034225e+04
Discount      4.869780e-03
Sales         1.089604e+06
Profit        5.146276e+04
dtype: float64

In [ ]:
# Combination of Mean & Variance
# Accepts "Numerical Data" only
df.agg(['mean','var'])